### ISSUE TITLE
Generated by hand? Or endpoint?

### ISSUE THREAD

**Issue by Noitidart** [michaelrhodes/stripe-pricing#1]
Is there an endpoint to get these numbers from stripe? Or was this generated by hand?

**Comment by PhilGale92** [comment]
@Noitidart  Just for futures peoples sake, looks like it was all generated via a html scrape via html-dom queries.

See
https://github.com/michaelrhodes/stripe-pricing/blob/master/bin/lib/pricing.js

So pretty high risk to rely on unless you feel like forking it and keeping it up to date if html classes change.

Theres also the fact it appears to query Stripes homepage to get a list of countries, which I can't see in the html anymore so i'm not sure if it will even re-build now days.

See https://github.com/michaelrhodes/stripe-pricing/blob/master/bin/lib/countries.js


While if it works i'm sure its good enough for personal projects and ive done a fair share of scraping... Feels too dirty for a prod build. Alas the search of recreating run-time stripe txn fees continues.

**Comment by Noitidart** [comment]
Thank you @PhilGale92!
